### ISSUE TITLE
Iniciar o desenvolvimento em Android

### ISSUE THREAD

**Issue by masmangan** [luiscasseres/esii_luis_casseres#1]

**Comment by luiscasseres** [comment]
Escolher a plataforma de desenvolvimento: Android Studio
Criar projeto no Android Sutdio: PrjWhatsApp
Criar view inicial 1.0 (Header sem ícones| Message Area | Voice Button).

**Comment by luiscasseres** [comment]
Escolhida a plataforma de desenvolvimento: Android Suite
Iniciado a construção da interface
